#!/bin/sh
#
# Maintains a tree-hash as on-disk checksum files.
#
# MIT 2-clause <nick@kousu.ca> 2025
#
# Run as:
# fs-integrity managed-folder/
#
# Verify checksums:
# find managed-folder/ -name checksums.sha256sum -type f | while read chk; do awk -v PREFIX=$(dirname $chk) '{print $1, PREFIX "/" $2}' $chk; done | sha256sum -c

# TODO:
# - [ ] should we catch move and create and modify?
#    Using close_write is a poor-man's debounce.
#    (but even it doesn't debounce everything);
#    What about long running downloads? Should we checksum them halfway?
# - [ ] detect and fill missing checksums on boot?
#   - maybe a separate script is better ...
# - [ ] use b2sum instead of sha256sum
#   - faster
#   - less portable?

debounce() {
  # debounce events from inotifywait
  # for a given path/file, wait for timeout to elapse and only output the *last* event seen
  #
  # Lots of apps (editors, especially) write tmp files which only exist for a
  # split second in order to guarantee atomic writes ( in fact we do this below ).
  # It's very bad to trigger redundant hashing, so wait for files to settle.

  timeout=${1:-3}; shift
  declare -A actions seen
  while true; do
    now=$(date +%s)

    # read and cache an event; but proceed if none within timeout
    if read -t "$timeout" -r path action file; then
      echo "==> input: $path $action $file" >&2
      k="${path}/${file}"
      actions[$k]="$action" # because . = ./ recovering them is ambiguous
      seen[$k]="$now"
    fi

    # output settled events
    for k in "${!seen[@]}"; do
      echo "==> checking: $k, ${seen[$k]}, $(( $now - ${seen[$k]} ))s ago" >&2
      if [ $(( $now - ${seen[$k]} )) -ge "$timeout" ]; then
        printf "%s %s %s\n" "$(dirname "$k")" "${actions[$k]}" "$(basename "$k")"
        unset actions[$k] seen[$k]
      fi
    done
  done
}


inotifywait -m -r -e close_write,delete "$@" | debounce 10 |
#inotifywait -m -r -e create,close_write,modify,move,delete --exclude "^checksums\.sha256sum\.tmp$" $@ |
while read path action file; do

  #echo "$path" "$action" "$file" >/dev/stderr  # DEBUG

  # checksum child checksum
  if [ "$file" = "checksums.sha256sum" ]; then
      if [ $(realpath --relative-to=. "$path") = "." ]; then
          # root of the tree, avoid recursing
          continue
      fi
      # shift the subfolder
      file=$(basename "$path")/"$file"
      path=$(dirname "$path")
  elif [ "$file" = ".checksums.sha256sum.tmp" ]; then
      # avoid recursing
      continue
  fi

	(
	# drop old checksum for $file (and, if 'delete', drop it entirely)
	export file
	cat "${path}/checksums.sha256sum" | awk '$2 != ENVIRON["file"]'

  if [ "$action" != "DELETE" ]; then
    # recompute checksum for the file
    (set -x; cd "$path" && sha256sum "$file") | tee /dev/stderr
  fi
  ) | sort -k 2 > "${path}/.checksums.sha256sum.tmp"

	# atomic mv
  mv "${path}/.checksums.sha256sum.tmp" "${path}/checksums.sha256sum"
	# hash should recurse *up* parent folders
	# #since inotify will notice the update
done
