#!/bin/sh
#
# Maintains a tree-hash as on-disk checksum files.
#
# MIT 2-clause <nick@kousu.ca> 2025
#
# Run as:
# wurmsum-watch managed-folder/


# TODO:
# - [ ] should we catch move and create and modify?
#    Using close_write is a poor-man's debounce.
#    (but even it doesn't debounce everything);
#    What about long running downloads? Should we checksum them halfway?
# - [ ] detect and fill missing checksums on boot?
#   - maybe a separate script is better ...
#   - but don't delete checksums for missing files, nor update checksums for changed files: those could represent corruption.
#
# - [ ] use b2sum instead of sha256sum
#   - faster
#   - less portable?
# - [ ] test with filenames with weird characters
# - [ ] files/folders with trailing newlines in their names don't work because shell strips trailing whitespace
#    I don't know if I can fix this without switching languages
# - [ ] Use paired MOVED_FROM/MOVED_TO to move the pre-computed checksum instead of recomputing it
#    Tricky though.

set -eo pipefail

targets=("${@:-./}")

debounce() {
  # debounce events from inotifywait
  # for a given path/file, wait for timeout to elapse and only output the *last* event seen
  #
  # Lots of apps (editors, especially) write tmp files which only exist for a
  # split second in order to guarantee atomic writes ( in fact we do this below ).
  # It's very bad to trigger redundant hashing, so wait for files to settle.

  timeout=${1:-3}; shift
  declare -A actions seen
  while true; do
    now=$(date +%s)

    # read and cache an event; but proceed if none within timeout
    if IFS=$'\n' read -t "$timeout" -d '' -r action path; then
      #echo "==> input: |$action| |$path|" >&2  # DEBUG
      actions["$path"]="$action" # because . = ./ recovering them is ambiguous
      seen["$path"]="$now"
    fi

    # output settled events
    for path in "${!seen[@]}"; do
      #echo "==> checking: $path, ${seen["$path"]}, $(( $now - ${seen["$path"]} ))s ago" >&2
      if [ $(( $now - ${seen["$path"]} )) -ge "$timeout" ]; then
        # echo "==> outputting |$path|" >&2 # DEBUG
        printf "%s\n%s\0" "${actions["$path"]}" "$path"
        unset actions["$path"] seen["$path"]
      fi
    done
  done
}


inotifywait -m -r -e close_write,move,delete --format "%e%n%w%f%0" "${targets[@]}" |
debounce 5 |
while IFS=$'\n' read -d '' -r action path; do

  #echo "==> input: |$action| |$path|" >&2 # DEBUG

  # we do this annoying parsing dance to handle weird characters like spaces and newlines in filenames
  # though we still cannot handle _trailing_ newlines
  file="$(basename "$path")"
  _path="$(dirname "$path")"

  #echo "path=|$path|, action=|$action|, file=|$file|, _path=|$_path|" >/dev/stderr  # DEBUG

  if [ "$file" = ".SHA256SUMS" ]; then
    # checksum children recursively:
    # .SHA256SUMS contains
    # - child1/.SHA256SUMS
    # - child2/.SHA256SUMS

    if [ "$(realpath --relative-to=. "$_path")" = "." ]; then
        # root of the tree, avoid recursing
        continue
    fi

    # shift the subfolder into $file
    file="$(basename "$_path")/$file"
    _path="$(dirname "$_path")"
  elif [ "$file" = ".SHA256SUMS.tmp" ]; then
    # avoid recursing
    continue
  fi

  (
    if [ "$action" != "DELETE" ] && [ "$action" != "MOVED_FROM" ]; then
      # recompute checksum for the file
      if [ "$(basename "$file")" != ".SHA256SUMS" ]; then
        # status message
        echo "Clutching in hoard: ${path}" >&2
      fi
      (cd "$_path" && sha256sum "$file") # | (echo -n "${_path}/.SHA256SUMS:" > /dev/stderr; tee /dev/stderr)
    else
      if [ "$(basename "$file")" != ".SHA256SUMS" ]; then
        # status message
        echo "Spilling from hoard: ${path}" >&2
      fi
    fi

    # drop old checksum for $file (and, if 'delete', drop it entirely)
    #
    # sha256sum encodes newlines as \n
    shasum_filename=$(printf "%s" "$file" | sed -z 's/\n/\\n/g')
    export shasum_filename
    if [ -f "${_path}/.SHA256SUMS" ]; then
      cat "${_path}/.SHA256SUMS" | while read -r s f; do
        if [ "$f" = "$shasum_filename" ]; then continue; fi
        printf "%s  %s\n" "$s" "$f"
      done
    fi
  ) | sort -k 2 > "${_path}/.SHA256SUMS.tmp"

	# atomic mv or delete
  if [ -s "${_path}/.SHA256SUMS.tmp" ]; then
    mv "${_path}/.SHA256SUMS.tmp" "${_path}/.SHA256SUMS"
  else
    # empty file => go away checksums
    rm -f "${_path}/.SHA256SUMS.tmp" "${_path}/.SHA256SUMS"
  fi
	# hash should recurse *up* parent folders
	# #since inotify will notice the update
done
