#!/bin/sh
#

targets=("${@:-./}")

find "${targets[@]}" -name .SHA256SUMS -type f |
while read chk; do
  # merge all checksums
  #
  PREFIX="$(dirname "$chk")"
  cat "$chk" | while read -r s f; do
    printf "%s %s/%s\n" "$s" "$PREFIX" "$f"
  done
done |
sort --key=2 |
#tee /dev/stderr | # DEBUG
sha256sum -c
