#!/bin/sh
#

TARGETS=("${@:-.}")
find "${TARGETS[@]}" -type d |
while read -r d; do
  ( cd "$d";
  # compute files on disk minus files in .SHA256SUMS
  # hash only the ones just on disk
   comm -z -23 \
     <(find . -maxdepth 1 -type f ! -name .SHA256SUMS -print0 | sed  -z 's/^.\///' | sort -z) \
     <(if [ -f .SHA256SUMS ]; then cut -f 3- -d ' ' .SHA256SUMS; fi  |  tr '\n' '\0' | sed -z 's/\\n/\n/g' | sort -z ) \
  | xargs -n1 -t -r -0 sha256sum >> .SHA256SUMS
 );
done
